# 【Q079】componentDidCatch


::: tip Issue
欢迎在 Gtihub Issue 中回答此问题: [Issue 79](https://github.com/kangyana/daily-question/issues/79)
:::

::: tip Author
回答者: [kangyana](https://github.com/kangyana)
:::
## 1. ErrorBoundary
`ErrorBoundary`（错误边界）是 React 组件，它会在其子组件树中的任何位置捕获 JavaScript 错误，
并记录这些错误，展示降级 UI 而不是崩溃的组件树。
`Error boundaries` 组件会捕获在渲染期间，在生命周期方法以及其整个树的构造函数中发生的错误。

如果 `class` 组件定义了生命周期方法 `static getDerivedStateFromError()` 或 `componentDidCatch()` 中的任何一个（或两者），
它就成为了 `Error boundaries`。
通过生命周期更新 `state` 可让组件捕获树中未处理的 JavaScript 错误并展示降级 UI。

仅使用 `Error boundaries` 组件来从意外异常中恢复的情况；不要将它们用于流程控制。
::: tip Author
回答者: [kangyana](https://github.com/kangyana)
:::
## 2. static getDerivedStateFromError()
```javascript
static getDerivedStateFromError(error)
```

此生命周期会在后代组件抛出错误后被调用。 它将抛出的错误作为参数，并返回一个值以更新 `state`。

```javascript
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // 更新 state 使下一次渲染可以显降级 UI
    return { hasError: true };
  }

  render() {
    if (this.state.hasError) {
      // 你可以渲染任何自定义的降级  UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

### 注意
`getDerivedStateFromError()` 会在渲染阶段调用，因此不允许出现副作用。
 如遇此类情况，请改用 `componentDidCatch()`。
::: tip Author
回答者: [kangyana](https://github.com/kangyana)
:::
## 3. componentDidCatch
```javascript
componentDidCatch(error, info)
```

此生命周期在后代组件抛出错误后被调用。 它接收两个参数：

- `error` —— 抛出的错误。
- `info` —— 带有 `componentStack key` 的对象，其中包含 **有关组件引发错误的栈信息**。

`componentDidCatch()` 会在“提交”阶段被调用，因此允许执行副作用。
 它应该用于记录错误之类的情况：
 
```javascript
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // 更新 state 使下一次渲染可以显示降级 UI
    return { hasError: true };
  }

  componentDidCatch(error, info) {
    // "组件堆栈" 例子:
    //   in ComponentThatThrows (created by App)
    //   in ErrorBoundary (created by App)
    //   in div (created by App)
    //   in App
    logComponentStackToMyService(info.componentStack);
  }

  render() {
    if (this.state.hasError) {
      // 你可以渲染任何自定义的降级 UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children;
  }
}
```

React 的开发和生产构建版本在 `componentDidCatch()` 的方式上有轻微差别。

在开发模式下，错误会冒泡至 `window`，这意味着任何 `window.onerror` 或 `window.addEventListener('error', callback)` 会中断这些已经被 `componentDidCatch()` 捕获的错误。

相反，在生产模式下，错误不会冒泡，这意味着任何根错误处理器只会接受那些没有显式地被 `componentDidCatch()` 捕获的错误。

### 注意

如果发生错误，你可以通过调用 `setState` 使用 `componentDidCatch()` 渲染降级 UI，但在未来的版本中将不推荐这样做。
可以使用静态 `getDerivedStateFromError()` 来处理降级渲染。
